# Generated by Django 3.2.19 on 2023-06-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbform',
            table='usertable',
        ),
    ]
