# Generated by Django 3.2.19 on 2023-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_alter_dbform_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbform',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dbform',
            name='sign',
            field=models.ImageField(default=None, null=True, upload_to='signs/'),
        ),
    ]
