# Generated by Django 3.2.19 on 2023-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20230608_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbform',
            name='address',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
